config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}

  scope "/admin" do
    resources :users do
      resources :manholecovers
    end
    resources :manholecovers
  end

  resources :roles

  resources :users, only: [:show]

  resources :manholecovers

  resources :users do
    resources :manholecovers
  end

  mount Monologue::Engine, at: '/blog' 

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'instagram' => 'welcome#instagram'

  get 'manholecovers/city/:city' => 'manholecovers#city'
  get 'manholecovers/region/:region' => 'manholecovers#region'
  get 'manholecovers/country/:country' => 'manholecovers#country'
  get 'manholecovers/year/:year' => 'manholecovers#year'
  get 'manholecovers/keyword/:keyword' => 'manholecovers#keywords'

  get 'users/:id/collection' => 'users#collection', :as => :collection_user

  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'

  match '*path', via: :all, to: 'errors#not_found'

end

app/models/manholecover.rb
class Manholecover < ActiveRecord::Base
  belongs_to :user

  has_attached_file :manhole_img,
    :styles => {:small => '320x320>', :large => '640x640>'},
    :storage => :s3,
    :bucket => ENV['S3_BUCKET_NAME'],
    :s3_credentials => S3_CREDENTIALS

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :manhole_img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :manhole_img, :matches => [/png\Z/, /jpe?g\Z/]
  validates_with AttachmentSizeValidator, :attributes => :manhole_img, :less_than => 2.megabytes
end

app/controllers/manholecovers_controller.rb
class ManholecoversController < ApplicationController
  # before_filter :authenticate_user!, :except => [:show, :index, :city, :country, :region, :year, :keywords]
  # before_filter :authenticate_user!, :only => [:edit, :update, :destroy]
  # load_and_authorize_resource
  before_action :set_manholecover, only: [:show, :edit, :update, :destroy]

  # GET /users/1/manholecovers
  # GET /users/1/manholecovers.json
  def index
    if @user
      @user_name = User.find_by(id: params[:user_id]).name
      @manholecovers = @user.manholecovers
    else
      @user_name = "All Users"
      @manholecovers = Manholecover.all
    end
  end

  # GET /users/1/manholecovers/new
  def new
    @user = User.find_by(id: params[:user_id])
    # @manholecover = @user.manholecovers.new
    # something is wrong with the above line
  end

  # GET /manholecovers/1
  # GET /manholecovers/1.json
  def show
    @user = User.find(@manholecover.user_id)
    @manholecover = @user.manholecovers.find(params[:id])
    # get random manhole covers of the same color
    color = @manholecover.color
    manholes_of_same_color = Manholecover.all.select do |manhole_entry|
      manhole_entry["color"] == "#{color}"
    end
    @random_manhole_of_same_color1 = manholes_of_same_color.sample
    @random_manhole_of_same_color2 = manholes_of_same_color.sample
    @random_manhole_of_same_color3 = manholes_of_same_color.sample
  end

  # GET /users/1/manholecovers/1/edit
  def edit
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @manholecover = @user.manholecovers.find(params[:id])
    else
      @manholecover = Manholecover.find(params[:id])
    end
    authorize! :update, @manholecover
  end

  # GET /manholecovers/city/:city
  def city
    # binding.pry
    @city = params[:city].downcase
    @manholecovers = Manholecover.all
    @certain_city_array = @manholecovers.select do |manhole_entry|
      manhole_entry["city"].downcase == @city
    end
  end

  # GET /manholecovers/region/:region
  def region
    @region = params[:region].downcase
    @manholecovers = Manholecover.all
    @certain_region_array = @manholecovers.select do |manhole_entry|
      manhole_entry["region"].downcase == @region
    end
  end

  # GET /manholecovers/country/:country
  def country
    @country = params[:country].downcase
    @manholecovers = Manholecover.all
    @certain_country_array = @manholecovers.select do |manhole_entry|
      manhole_entry["country"].downcase == @country
    end
  end

  # GET /manholecovers/year/:year
  def year
    @year = params[:year].to_i
    @manholecovers = Manholecover.all
    @certain_year_array = @manholecovers.select do |manhole_entry|
      manhole_entry["year"] == @year
    end
  end

  # GET /manholecovers/keyword/:keyword
  def keywords
    @keyword = params[:keyword]
    @manholecovers = Manholecover.all
    @with_keyword_array = @manholecovers.select do |manhole_entry|
      manhole_entry["keywords"].include?"#{@keyword}"
    end
  end

  # POST /users/1/manholecovers
  # POST /users/1/manholecovers.json
  def create
    @user = User.find_by(id: params[:user_id])
    # binding.pry
    # @manholecover = Manholecover.new(manholecover_params)
    @manholecover.keywords = params[:manholecover][:keywords].downcase.split(", ")
    @manholecover.user_id = @user.id
    authorize! :create, @manho
    respond_to do |format|
      if @manholecover.save
        format.html { redirect_to user_manholecovers_path, notice: 'Manholecover was successfully created.' }
        format.json { render :show, status: :created, location: @manholecover }
      else
        format.html { render :new }
        format.json { render json: @user.manholecover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT users/1/manholecovers/1
  # PATCH/PUT users/1/manholecovers/1.json
  def update
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      # binding.pry
      input_keywords = params[:manholecover][:keywords].downcase.split(", ")
      @manholecover.update(keywords: input_keywords)
      # @manholecover.keywords_will_change!
      # @manholecover.attributes = params[:keywords]
      @manholecover.keywords_will_change!
      # @manholecover.save!
      respond_to do |format|
        if @manholecover.update(manholecover_params)
          format.html { redirect_to user_manholecover_path, notice: 'Manhole Cover was successfully updated.' }
          format.json { render :show, status: :ok, location: @manholecover }
        else
          format.html { render :edit }
          format.json { render json: @user.manholecover.errors, status: :unprocessable_entity }
        end
      end
    else
      input_keywords = params[:manholecover][:keywords].downcase.split(", ")
      @manholecover = Manholecover.find(params[:id])
      # @manholecover.update
      respond_to do |format|
        if @manholecover.update(manholecover_params)
          format.html { redirect_to manholecover_path, notice: 'Manhole Cover was successfully updated.' }
          format.json { render :show, status: :ok, location: @manholecover }
        else
          format.html { render :edit }
          format.json { render json: @manholecover.errors, status: :unprocessable_entity }
        end
      end
    end
    authorize! :update, @manholecover
  end

  # DELETE users/1/manholecovers/1
  # DELETE users/1/manholecovers/1.json
  def destroy
    @user = User.find_by(id: params[:user_id])
    @manholecover = Manholecover.find(params[:id])
    authorize! :destroy, @manholecover
    @manholecover.delete
    respond_to do |format|
      format.html { redirect_to user_manholecovers_path, notice: 'Manholecover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manholecover
      @user = User.find_by(id: params[:user_id])
      @manholecover = Manholecover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manholecover_params
      params.require(:manholecover).permit(:id, :manhole_img, :country, :region, :city, :year, :color, :keywords, :notes, :featured, :user_id, :_method)
    end

end

app/helpers/manholecovers_helper.rb
module ManholecoversHelper
end

app/views/manholecovers/_form.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-1 col-lg-1"></div>
  <div class="col-xs-10 col-sm-10 col-lg-10">
    <%= form_for [@collector, @manholecover] do |f| %>
      <% if @manholecover.errors.any? %>
        <div id="error_explanation">
          <h2>This manhole cover can't be saved due to <%= pluralize(@manholecover.errors.count, "error") %></h2>

          <ul>
          <% @manholecover.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :manhole_img, "Image", :class => "form-label" %><br />
        <%= f.file_field :manhole_img %>
        <div class="form-field-desc">Upload your image.</div>
      </div>

      <div class="field">
        <%= f.label :country, :class => "form-label" %><br />
        <%= f.text_field :country, :class => "form_input", :maxlength => 50 %>
        <div class="form-field-desc">Choose one from the dropdown menu.</div>
      </div>

      <div class="field">
        <%= f.label :region, :class => "form-label" %><br />
        <%= f.text_field :region, :class => "form_input", :maxlength => 50 %>
        <div class="form-field-desc">Depending on the country,this can be a state, province, profecture, etc.</div>
      </div>

      <div class="field">
        <%= f.label :city, :class => "form-label" %><br />
        <%= f.text_field :city, :class => "form_input", :maxlength => 50 %>
        <div class="form-field-desc">Or a twon. If you have more specific geo info, put it in the keyword field instead.</div>
      </div>

      <div class="field">
        <%= f.label :year, :class => "form-label" %><br />
        <%= f.text_field :year, :placeholder => "YYYY", :maxlength => 4, :class => "form_input" %>
        <div class="form-field-desc">In the format of YYYY</div>
      </div>

      <div class="field">
        <%= f.label :color, :class => "form-label" %><br />
        <%= f.select :color, options_for_select(["Black", "Grey", "White", "Red", "Orange", "Yellow", "Green", "Blue", "Purple", "Brown", "Other"], :class => "form_input") %>
        <div class="form-field-desc">Just pick one the covers the most area, or just choose "other" if you can't decide.</div>
      </div>

      <div class="field">
        <%= f.label :notes, :class => "form-label" %><br />
        <%= f.text_area :notes, :class => "form_input long_input" %>
        <div class="form-field-desc">Just write down one sentence or two.</div>
      </div>

      <div class="field">
        <%= f.label :keywords, :class => "form-label" %><br />
        <%= f.text_area :keywords, :placeholder => "Separate with comma", :class => "form_input long_input" %>
        <div class="form-field-desc">Separated by commas. Whatever characterizes this manhole cover, really.</div>
      </div>

      <br>

      <%= f.submit "UPDATE", :class => "actions" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "CANCEL", :back, :class => 'link-button' %>

    <% end %>
  </div>
</div>

app/views/manholecovers/city.html.erb
<div class="container">

  <!-- close button -->
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-lg-11"></div>
    <div class="col-xs-2 col-sm-2 col-lg-1">
      <%= link_to image_tag("nonmanholes/close.png", :class => "img-responsive close"), root_path%>
    </div>
  </div>

  <h3>Manhole Covers in the City of <%= @city.titleize %></h3>

  <!-- empty row -->
  <div class="row"><br></div>

  <div class="row">
    <% @certain_city_array.each_with_index do |manhole_entry| %>
      <a href="/users/<%= manhole_entry.user_id %>/manholecovers/<%= manhole_entry.id %>">
        <ul class="list-of-a-feature">
          <li><img src="<%= manhole_entry.manhole_img.url(:large) %>" class="img-responsive"></li>
        </ul>
      </a>
    <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/manholecovers/country.html.erb
<div class="container">
  <h3>Manhole Covers in the Country of <%= @country.titleize %></h3>
  <% @certain_country_array.each_with_index do |manhole_entry| %>
    <a href="/users/<%= manhole_entry.user_id %>/manholecovers/<%= manhole_entry.id %>">
      <ul class="list-of-a-feature">
        <li><img src="<%= manhole_entry.manhole_img.url(:small) %>"></li>
      </ul>
    </a>
  <% end %>
  <div class="clear"></div>
</div>

app/views/manholecovers/edit.html.erb
<div class="container">

  <!-- close button -->
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-lg-11"></div>
    <div class="col-xs-2 col-sm-2 col-lg-1">
      <%= link_to image_tag("nonmanholes/close.png", :class => "img-responsive close"), root_path%>
    </div>
  </div>

  <h3 style="padding-bottom: 30px;">Update a Manhole Cover</h3>

  <%= render 'form' %>

</div>

app/views/manholecovers/index.html.erb
<div class="container">
  <h3>Manhole Covers Collected by <%= @user_name %></h3>
  <% @manholecovers.each do |manholecover| %>
    <a href="/users/<%= manholecover.user_id%>/manholecovers/<%= manholecover["id"] %>">
      <ul class="list-of-a-feature">
        <li><img src="<%= manholecover.manhole_img.url(:small) %>"></li>
        <li><%= User.find_by(id: manholecover.user_id).name %></li>
        <li><%= link_to 'Show', manholecover %></li>
        <li>
          <% if can? :update, manholecover %>
            <%= link_to 'Edit', manholecover %>
          <% end %>
        </li>
        <li>
          <% if can? :destroy, manholecover %>
            <%= link_to 'Destroy', manholecover, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </li>
        <li>
          <% if can? :create, manholecover %>
            <%= link_to 'New Manholecover', new_manholecover_path %>
          <% end %>
        </li>
      </ul>
    </a>
  <% end %>
  <div class="clear"></div>
</div>

app/views/manholecovers/keywords.html.erb
<div class="container">
  <h3>Manhole Covers with the keyword of <%= @keyword %></h3>
  <% @with_keyword_array.each_with_index do |manhole_entry| %>
    <a href="/users/<%= manhole_entry.user_id %>/manholecovers/<%= manhole_entry.id %>">
      <ul class="list-of-a-feature">
        <li><img src="<%= manhole_entry.manhole_img.url(:small) %>"></li>
      </ul>
    </a>
  <% end %>
  <div class="clear"></div>
</div>

app/views/manholecovers/new.html.erb
<div class="container">

  <!-- close button -->
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-lg-11"></div>
    <div class="col-xs-2 col-sm-2 col-lg-1">
      <%= link_to image_tag("nonmanholes/close.png", :class => "img-responsive close"), root_path%>
    </div>
  </div>

  <h3 style="padding-bottom: 30px;">Add a New Manhole Cover</h3>

  <%= render 'form' %>

</div>

app/views/manholecovers/region.html.erb
<div class="container">
  <h3>Manhole Covers in the Region of <%= @region.titleize %></h3>
  <% @certain_region_array.each_with_index do |manhole_entry| %>
    <a href="/users/<%= manhole_entry.user_id %>/manholecovers/<%= manhole_entry.id %>">
      <ul class="list-of-a-feature">
        <li><img src="<%= manhole_entry.manhole_img.url(:small) %>"></li>
      </ul>
    </a>
  <% end %>
  <div class="clear"></div>
</div>

app/views/manholecovers/show.html.erb
<div class="container">

  <!-- close button -->
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-lg-11"></div>
    <div class="col-xs-2 col-sm-2 col-lg-1">
      <%= link_to image_tag("nonmanholes/close.png", :class => "img-responsive close"), root_path%>
    </div>
  </div>

  <!-- large manhole image  -->
  <div class="row">
    <div class="col-xs-10 col-sm-9 col-lg-9"><img class="img-responsive big_image img-circle" src="<%= @manholecover.manhole_img.url(:large) %>"></div>
    <div class="col-xs-2 col-sm-3 col-lg-3"></div>
  </div>

  <!-- empty row -->
  <div class="row"><br></div>

  <!-- description  -->
  <div class="row">
    <div class="col-xs-2 col-sm-7 col-lg-7"></div>
    <div class="col-xs-10 col-sm-5 col-lg-5 description">
      <div class="table-responsive">
        <table class="table">
          <tr>
            <td>
              <p class="meta_text">Collector:&nbsp;</p>
            </td>
            <td class="meta_content">
              <%= link_to @manholecover.user.name, collection_user_path %>
            </td>
          </tr>
          <tr>
            <td>
              <p class="meta_text" id="meta_year">Year:&nbsp;</p>
            </td>
            <td class="meta_content">
              <a href="/manholecovers/year/<%= @manholecover.year %>">
                <%= @manholecover.year %>
              </a>
            </td>
          </tr>
          <tr>
            <td>
              <p class="meta_text">Location:&nbsp;</p>
            </td>
            <td class="meta_content">
              <a href="/manholecovers/city/<%= @manholecover.city %>"><%= @manholecover.city %></a>,
              <a href="/manholecovers/region/<%= @manholecover.region %>"><%= @manholecover.region %></a>,
              <a href="/manholecovers/country/<%= @manholecover.country %>"><%= @manholecover.country %></a>
            </td>
          </tr>
          <tr>
            <td>
              <p class="meta_text" id="meta_info">Note:&nbsp;</p>
            </td>
            <td class="meta_content">
              <%= @manholecover.notes %>
            </td>
          </tr>
          <tr>
            <td>
              <p class="meta_text">Keywords:&nbsp;</p>
            </td>
            <td class="meta_content">
              <span class="meta_content">
                <% @manholecover.keywords.each do |keyword|%>
                  <a href="/manholecovers/keyword/<%= keyword %>">#<%= keyword %>&nbsp;</a>
                <% end %>
              </span>
            </td>
          </tr>
        </table>
      </div>

      <br>
      <% if @user_id %>
        <% if can? :update, @manholecover %>
          <%= link_to 'EDIT', edit_user_manholecover_path(@user, @manholecover), class: "link-button" %>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <% if can? :destroy, @manholecover %>
          <%= link_to 'DELETE', user_manholecover_path, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }, class: "link-button" %>
        <% end %>
      <% else %>
        <% if can? :update, @manholecover %>
          <%= link_to 'EDIT', edit_manholecover_path(@manholecover), class: "link-button" %>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <% if can? :destroy, @manholecover %>
          <%= link_to 'DELETE', manholecover_path, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }, class: "link-button" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row"><hr class="divider"></div>

  <div class="row">
    <div class="col-xs-4 col-sm-4 col-lg-4">
      <a href="/users/<%= @random_manhole_of_same_color1.user_id %>/manholecovers/<%= @random_manhole_of_same_color1.id %>"><img class="img-responsive img-circle small_image similar" src="<%= @random_manhole_of_same_color1.manhole_img.url(:small) %>"></a>
    </div>
    <div class="col-xs-4 col-sm-4 col-lg-4">
      <a href="/users/<%= @random_manhole_of_same_color2.user_id %>/manholecovers/<%= @random_manhole_of_same_color2["id"] %>"><img class="img-responsive img-circle small_image similar" src="<%= @random_manhole_of_same_color2.manhole_img.url(:small) %>"></a>
    </div>
    <div class="col-xs-4 col-sm-4 col-lg-4">
      <a href="/users/<%= @random_manhole_of_same_color3.user_id %>/manholecovers/<%= @random_manhole_of_same_color3["id"] %>"><img class="img-responsive img-circle small_image similar" src="<%= @random_manhole_of_same_color3.manhole_img.url(:small) %>"></a>
    </div>
  </div>
</div>

app/views/manholecovers/year.html.erb
<div class="container">
  <h3>Manhole Covers Collected in the Year of <%= @year %></h3>
  <% @certain_year_array.each do |manhole_entry| %>
    <a href="/collectors/<%= manhole_entry.user_id %>/manholecovers/<%= manhole_entry.id %>">
      <ul class="list-of-a-feature">
        <li><img src="<%= manhole_entry.manhole_img.url(:small) %>"></li>
      </ul>
    </a>
  <% end %>
  <div class="clear"></div>
</div>