config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}

  scope "/admin" do
    resources :users do
      resources :manholecovers
    end
    resources :manholecovers
  end

  resources :roles

  resources :users, only: [:show]

  resources :manholecovers

  resources :users do
    resources :manholecovers
  end

  mount Monologue::Engine, at: '/blog' 

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'instagram' => 'welcome#instagram'

  get 'manholecovers/city/:city' => 'manholecovers#city'
  get 'manholecovers/region/:region' => 'manholecovers#region'
  get 'manholecovers/country/:country' => 'manholecovers#country'
  get 'manholecovers/year/:year' => 'manholecovers#year'
  get 'manholecovers/keyword/:keyword' => 'manholecovers#keywords'

  get 'users/:id/collection' => 'users#collection', :as => :collection_user

  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'

  match '*path', via: :all, to: 'errors#not_found'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    if @roles.users.legnth == 0
      @associated_users = "None"
    else
      @associated_users = @role.users.map(&:name).join(", ")
    end
  end

  # GET /roles/new
  def new
    # @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    # @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_role
    #   @role = Role.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for(@role) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Assosciated users:</strong>
  <%= @associated_users %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>